-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 11:35:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TaskManagementDB
-- -----------------------------------------------------

CREATE SCHEMA taskmanagementdb;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `userID` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `accountID` INT NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `status` VARCHAR(20) NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`accountID`),
  INDEX `userID_idx` (`userID` ASC),
  CONSTRAINT `FK_Account_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Status` ;

CREATE TABLE IF NOT EXISTS `Status` (
  `statusID` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`statusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schedule` ;

CREATE TABLE IF NOT EXISTS `Schedule` (
  `scheduleID` INT NOT NULL AUTO_INCREMENT,
  `startDateTime` DATETIME NOT NULL,
  `endDateTime` DATETIME NOT NULL,
  PRIMARY KEY (`scheduleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Task` ;

CREATE TABLE IF NOT EXISTS `Task` (
  `taskID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `dateTimeScheduled` DATETIME NULL,
  `statusID` INT NULL,
  `userID` INT NULL,
  `scheduleID` INT NULL,
  `recurrenceRuleID` INT NULL,
  PRIMARY KEY (`taskID`),
  INDEX `FK_Task_userID_idx` (`userID` ASC),
  INDEX `FK_Task_statusID_idx` (`statusID` ASC),
  INDEX `FK_Task_scheduleID_idx` (`scheduleID` ASC),
  CONSTRAINT `FK_Task_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Task_statusID`
    FOREIGN KEY (`statusID`)
    REFERENCES `Status` (`statusID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Task_scheduleID`
    FOREIGN KEY (`scheduleID`)
    REFERENCES `Schedule` (`scheduleID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tag` ;

CREATE TABLE IF NOT EXISTS `Tag` (
  `tagID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `color` VARCHAR(20) NULL,
  `userID` INT NULL,
  `Tagcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tagID`),
  INDEX `FK_Tag_userID_idx` (`userID` ASC),
  CONSTRAINT `FK_Tag_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project` ;

CREATE TABLE IF NOT EXISTS `Project` (
  `projectID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `dueDate` DATETIME NULL,
  `description` TEXT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`projectID`),
  INDEX `FK_Project_userID_idx` (`userID` ASC),
  CONSTRAINT `FK_Project_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reminder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reminder` ;

CREATE TABLE IF NOT EXISTS `Reminder` (
  `reminderID` INT NOT NULL AUTO_INCREMENT,
  `dueDate` DATETIME NOT NULL,
  `notificationMethod` VARCHAR(45) NOT NULL,
  `message` TEXT NULL,
  `taskID` INT NOT NULL,
  PRIMARY KEY (`reminderID`),
  INDEX `FK_Reminder_taskID_idx` (`taskID` ASC),
  CONSTRAINT `FK_Reminder_taskID`
    FOREIGN KEY (`taskID`)
    REFERENCES `Task` (`taskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subtask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Subtask` ;

CREATE TABLE IF NOT EXISTS `Subtask` (
  `subTaskID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `statusID` INT NOT NULL,
  `dateTimeScheduled` DATETIME NULL,
  `parentTaskID` INT NULL,
  `Subtaskcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subTaskID`),
  INDEX `FK_Subtask_statusID_idx` (`statusID` ASC),
  INDEX `FK_Subtask_parentTaskID_idx` (`parentTaskID` ASC),
  CONSTRAINT `FK_Subtask_statusID`
    FOREIGN KEY (`statusID`)
    REFERENCES `Status` (`statusID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Subtask_parentTaskID`
    FOREIGN KEY (`parentTaskID`)
    REFERENCES `Task` (`taskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskDependency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskDependency` ;

CREATE TABLE IF NOT EXISTS `TaskDependency` (
  `predecessorTaskID` INT NOT NULL,
  `successorTaskID` INT NOT NULL,
  `dependencyType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`predecessorTaskID`, `successorTaskID`),
  INDEX `FK_TaskDependency_sucessorTaskID_idx` (`successorTaskID` ASC),
  CONSTRAINT `FK_TaskDependency_predecessorTaskID`
    FOREIGN KEY (`predecessorTaskID`)
    REFERENCES `Task` (`taskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TaskDependency_sucessorTaskID`
    FOREIGN KEY (`successorTaskID`)
    REFERENCES `Task` (`taskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Device Table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Device Table` ;

CREATE TABLE IF NOT EXISTS `Device Table` (
  `deviceID` INT NOT NULL AUTO_INCREMENT,
  `deviceType` VARCHAR(45) NOT NULL,
  `operatingSystem` VARCHAR(45) NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`deviceID`),
  INDEX `FK_DeviceTable_userID_idx` (`userID` ASC),
  CONSTRAINT `FK_DeviceTable_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserPreferences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserPreferences` ;

CREATE TABLE IF NOT EXISTS `UserPreferences` (
  `preferenceID` INT NOT NULL AUTO_INCREMENT,
  `notificationSettings` VARCHAR(100) NOT NULL,
  `defaultReminderTimes` TIME NULL,
  `defaultTaskProperties` TEXT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`preferenceID`),
  INDEX `FK_UserPreferences_userID_idx` (`userID` ASC),
  CONSTRAINT `FK_UserPreferences_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserSettings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserSettings` ;

CREATE TABLE IF NOT EXISTS `UserSettings` (
  `settingsID` INT NOT NULL AUTO_INCREMENT,
  `privacySettings` VARCHAR(100) NOT NULL,
  `accountSecuritySettings` VARCHAR(100) NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`settingsID`),
  INDEX `FK_UserSettings_userID_idx` (`userID` ASC),
  CONSTRAINT `FK_UserSettings_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Note` ;

CREATE TABLE IF NOT EXISTS `Note` (
  `noteID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `context` TEXT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `taskID` INT NOT NULL,
  PRIMARY KEY (`noteID`),
  INDEX `FK_Note_taskID_idx` (`taskID` ASC),
  CONSTRAINT `FK_Note_taskID`
    FOREIGN KEY (`taskID`)
    REFERENCES `Task` (`taskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Attachment` ;

CREATE TABLE IF NOT EXISTS `Attachment` (
  `attachmentID` INT NOT NULL AUTO_INCREMENT,
  `fileORLink` VARCHAR(255) NOT NULL,
  `metadata` TEXT NULL,
  `fileSize` INT NOT NULL,
  `taskID` INT NULL,
  `Attachmentcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`attachmentID`),
  INDEX `FK_Attachment_taskID_idx` (`taskID` ASC),
  CONSTRAINT `FK_Attachment_taskID`
    FOREIGN KEY (`taskID`)
    REFERENCES `Task` (`taskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RecurrenceRule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RecurrenceRule` ;

CREATE TABLE IF NOT EXISTS `RecurrenceRule` (
  `recurrenceRuleID` INT NOT NULL AUTO_INCREMENT,
  `timesOfRecurrence` INT NOT NULL,
  `stateDateTime` DATETIME NOT NULL,
  `endDateTime` DATETIME NOT NULL,
  `frequency` VARCHAR(45) NOT NULL,
  `taskID` INT NOT NULL,
  PRIMARY KEY (`recurrenceRuleID`),
  INDEX `FK_RecurrenceRule_taskID_idx` (`taskID` ASC),
  CONSTRAINT `FK_RecurrenceRule_taskID`
    FOREIGN KEY (`taskID`)
    REFERENCES `Task` (`taskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaskInstance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TaskInstance` ;

CREATE TABLE IF NOT EXISTS `TaskInstance` (
  `taskInstanceID` INT NOT NULL AUTO_INCREMENT,
  `statusID` INT NOT NULL,
  `scheduleID` INT NULL,
  `recurrenceRuleID` INT NULL,
  `completionDateTime` DATETIME NULL,
  PRIMARY KEY (`taskInstanceID`),
  INDEX `FK_TaskInstance_statusID_idx` (`statusID` ASC),
  INDEX `FK_TaskInstance_scheduleID_idx` (`scheduleID` ASC),
  INDEX `FK_TaskInstance_recurrenceRuleID_idx` (`recurrenceRuleID` ASC),
  CONSTRAINT `FK_TaskInstance_statusID`
    FOREIGN KEY (`statusID`)
    REFERENCES `Status` (`statusID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TaskInstance_scheduleID`
    FOREIGN KEY (`scheduleID`)
    REFERENCES `Schedule` (`scheduleID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TaskInstance_recurrenceRuleID`
    FOREIGN KEY (`recurrenceRuleID`)
    REFERENCES `RecurrenceRule` (`recurrenceRuleID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CustomField`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomField` ;

CREATE TABLE IF NOT EXISTS `CustomField` (
  `customFieldID` INT NOT NULL AUTO_INCREMENT,
  `fieldType` VARCHAR(45) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `userID` INT NOT NULL,
  `defaultValue` TEXT NULL,
  PRIMARY KEY (`customFieldID`),
  INDEX `FK_CustomField_userID_idx` (`userID` ASC),
  CONSTRAINT `FK_CustomField_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Context`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Context` ;

CREATE TABLE IF NOT EXISTS `Context` (
  `contextID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`contextID`),
  INDEX `FK_Context_userID_idx` (`userID` ASC),
  CONSTRAINT `FK_Context_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Notification` ;

CREATE TABLE IF NOT EXISTS `Notification` (
  `notificationID` INT NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NOT NULL,
  `userID` INT NOT NULL,
  `taskID` INT NOT NULL,
  `message` TEXT NULL,
  `reminderID` INT NULL,
  `contextID` INT NULL,
  PRIMARY KEY (`notificationID`),
  INDEX `FK_Notification_userID_idx` (`userID` ASC),
  INDEX `FK_Notification_taskID_idx` (`taskID` ASC),
  INDEX `FK_Notification_reminderID_idx` (`reminderID` ASC),
  INDEX `FK_Notification_contextID_idx` (`contextID` ASC),
  CONSTRAINT `FK_Notification_userID`
    FOREIGN KEY (`userID`)
    REFERENCES `User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Notification_taskID`
    FOREIGN KEY (`taskID`)
    REFERENCES `Task` (`taskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Notification_reminderID`
    FOREIGN KEY (`reminderID`)
    REFERENCES `Reminder` (`reminderID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Notification_contextID`
    FOREIGN KEY (`contextID`)
    REFERENCES `Context` (`contextID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
