-- =============================================================================
-- Schema Updates for TaskManagementDB
-- Apply these ALTER statements to an existing database.
-- =============================================================================

USE taskmanagementdb;

-- -----------------------------------------------------------------------------
-- 1. User.userID — add AUTO_INCREMENT so inserts don't require a manual ID
-- -----------------------------------------------------------------------------
ALTER TABLE `User`
  MODIFY `userID` INT NOT NULL AUTO_INCREMENT;


-- -----------------------------------------------------------------------------
-- 2. Drop scaffold placeholder columns
--    These were generated by MySQL Workbench and have no business meaning.
--    All three are NOT NULL with no DEFAULT, forcing every insert to supply
--    the literal string 'default_value'.
-- -----------------------------------------------------------------------------
ALTER TABLE `Tag`        DROP COLUMN `Tagcol`;
ALTER TABLE `Subtask`    DROP COLUMN `Subtaskcol`;
ALTER TABLE `Attachment` DROP COLUMN `Attachmentcol`;


-- -----------------------------------------------------------------------------
-- 3. Fix the RecurrenceRule ↔ Task circular dependency
--
--    Current state (broken):
--      RecurrenceRule.taskID  → Task.taskID   (FK enforced)
--      Task.recurrenceRuleID  → (nothing)      (column exists, no constraint)
--
--    The correct direction: a Task optionally follows a RecurrenceRule.
--    RecurrenceRule should be an independent entity; Task references it.
--
--    Fix: drop taskID from RecurrenceRule, add FK on Task.recurrenceRuleID.
-- -----------------------------------------------------------------------------

-- Step A: drop the old FK and column from RecurrenceRule
ALTER TABLE `RecurrenceRule`
  DROP FOREIGN KEY `FK_RecurrenceRule_taskID`;

ALTER TABLE `RecurrenceRule`
  DROP INDEX `FK_RecurrenceRule_taskID_idx`;

ALTER TABLE `RecurrenceRule`
  DROP COLUMN `taskID`;

-- Step B: add the missing index + FK on Task.recurrenceRuleID
ALTER TABLE `Task`
  ADD INDEX `FK_Task_recurrenceRuleID_idx` (`recurrenceRuleID` ASC);

ALTER TABLE `Task`
  ADD CONSTRAINT `FK_Task_recurrenceRuleID`
    FOREIGN KEY (`recurrenceRuleID`)
    REFERENCES `RecurrenceRule` (`recurrenceRuleID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE;


-- -----------------------------------------------------------------------------
-- 4. Add projectID to Task so tasks can belong to a project
--    (Project table already exists; this was simply missing)
-- -----------------------------------------------------------------------------
ALTER TABLE `Task`
  ADD COLUMN `projectID` INT NULL AFTER `recurrenceRuleID`;

ALTER TABLE `Task`
  ADD INDEX `FK_Task_projectID_idx` (`projectID` ASC);

ALTER TABLE `Task`
  ADD CONSTRAINT `FK_Task_projectID`
    FOREIGN KEY (`projectID`)
    REFERENCES `Project` (`projectID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE;


-- -----------------------------------------------------------------------------
-- 5. Add TaskTag join table — allows many-to-many Task ↔ Tag assignments
--    (Tag was user-scoped but had no way to attach to a specific task)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaskTag` (
  `taskID` INT NOT NULL,
  `tagID`  INT NOT NULL,
  PRIMARY KEY (`taskID`, `tagID`),
  INDEX `FK_TaskTag_tagID_idx` (`tagID` ASC),
  CONSTRAINT `FK_TaskTag_taskID`
    FOREIGN KEY (`taskID`)
    REFERENCES `Task` (`taskID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TaskTag_tagID`
    FOREIGN KEY (`tagID`)
    REFERENCES `Tag` (`tagID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------------------------------
-- 6. Add createdAt to Task for creation-order sorting and audit trail
-- -----------------------------------------------------------------------------
ALTER TABLE `Task`
  ADD COLUMN `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  AFTER `dateTimeScheduled`;


-- -----------------------------------------------------------------------------
-- 7. Add a compound index on Task(userID, dateTimeScheduled) —
--    the most common query pattern (user's tasks in chronological order)
--    currently hits two separate indexes. A compound index covers it directly.
-- -----------------------------------------------------------------------------
ALTER TABLE `Task`
  ADD INDEX `idx_Task_userID_dateTimeScheduled` (`userID` ASC, `dateTimeScheduled` ASC);


-- -----------------------------------------------------------------------------
-- 8. Add priority to Task — allows LOW / MEDIUM / HIGH urgency classification
-- -----------------------------------------------------------------------------
ALTER TABLE `Task`
  ADD COLUMN `priority` VARCHAR(20) NULL DEFAULT NULL
  CHECK (`priority` IN ('LOW', 'MEDIUM', 'HIGH'));


-- -----------------------------------------------------------------------------
-- 9. Make Project.userID nullable so projects can be created without a user
--    (required until user auth is implemented)
-- -----------------------------------------------------------------------------
ALTER TABLE `Project`
  MODIFY `userID` INT NULL;
