spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/taskmanagementdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:taskuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:taskpass}
server.address=0.0.0.0
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
